// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcDq4Ey_lD9d-2Rp0I-DmqjRXr7lvR1Lc',
    appId: '1:661707570114:android:cd61835d19e7e193a5345b',
    messagingSenderId: '661707570114',
    projectId: 'our-nakla',
    databaseURL: 'https://our-nakla-default-rtdb.firebaseio.com',
    storageBucket: 'our-nakla.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHg7lytpH-KEh2viq4hLJnnwkbEKyWAjo',
    appId: '1:661707570114:web:dffb87c243ced681a5345b',
    messagingSenderId: '661707570114',
    projectId: 'our-nakla',
    authDomain: 'our-nakla.firebaseapp.com',
    databaseURL: 'https://our-nakla-default-rtdb.firebaseio.com',
    storageBucket: 'our-nakla.appspot.com',
    measurementId: 'G-PC5BCEH56T',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE5QFZL5fNpMzo-GgWuA5NQo8XdLTJLas',
    appId: '1:661707570114:ios:ff8b7a74b16003efa5345b',
    messagingSenderId: '661707570114',
    projectId: 'our-nakla',
    databaseURL: 'https://our-nakla-default-rtdb.firebaseio.com',
    storageBucket: 'our-nakla.appspot.com',
    iosBundleId: 'com.my.smart.nakla',
  );

}