// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCBw92fNxaptKppYI1IPwLjFNCiOO64bc',
    appId: '1:361744312172:android:dce3dbea20803410faf549',
    messagingSenderId: '361744312172',
    projectId: 'spice-box-takeway',
    storageBucket: 'spice-box-takeway.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyB7cf7E5gQwgr1QuTxgWL1eQC2SNefVYFA",
      authDomain: "spice-box-takeway.firebaseapp.com",
      projectId: "spice-box-takeway",
      storageBucket: "spice-box-takeway.firebasestorage.app",
      messagingSenderId: "361744312172",
      appId: "1:361744312172:web:b5703a352dd57ef2faf549",
      measurementId: "G-33PJ6ZLNQ0");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5DdDeG2hU913hN1OffbfVHCURSrPvaB8',
    appId: '1:361744312172:ios:a11b0656ea49ccbafaf549',
    messagingSenderId: '361744312172',
    projectId: 'spice-box-takeway',
    storageBucket: 'spice-box-takeway.firebasestorage.app',
    iosBundleId: 'com.spice.box.skylonit',
  );
}
